# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{geo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brent Theisen"]
  s.date = %q{2011-05-12}
  s.description = %q{City, county, state and postal code models with seed data packaged in a gem for use in Rails.}
  s.email = %q{brent@designspiders.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/models/geo/city.rb",
    "app/models/geo/county.rb",
    "app/models/geo/postal_code.rb",
    "app/models/geo/state.rb",
    "data/zipcodes_2006/README.txt",
    "data/zipcodes_2006/zip_distance.pl",
    "data/zipcodes_2006/zip_insert.pl",
    "data/zipcodes_2006/zip_range.pl",
    "data/zipcodes_2006/zipcode_sql.txt",
    "data/zipcodes_2006/zipcodes_2006.txt",
    "db/seeds.rb",
    "geo.gemspec",
    "lib/generators/geo/install/install_generator.rb",
    "lib/generators/geo/install/templates/create_geo_tables.rb",
    "lib/geo.rb",
    "lib/tasks/load_seed.rake",
    "test/helper.rb",
    "test/test_geo.rb"
  ]
  s.homepage = %q{http://github.com/brenttheisen/geo}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{City, county, state and postal code models with seed data packaged in a gem for use in Rails.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

